services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: projecqrs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - another_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  another_postgres_data:
