spring:
  application:
    name: proje.cqrs
  datasource:
    url: "jdbc:postgresql://localhost:5432/projecqrs"
    username: admin
    password: secret
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      hibernate:
        ddl-auto: create
  server:
    port: 8080


