spring:
  application:
    name: proje.cqrs
  datasource:
    url: "jdbc:postgresql://localhost:5432/projecqrs"
    username: admin
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080
jwt:
  expiration : 600000
  secret : "xH2T5oQkps9kVMrLxEWCNN1fIVApRLyBJdqPmD2akJmLele48q2Q3M6tua6kmcCd"



